### ISSUE TITLE
Can we download all provisioning then re-use their uuid directly in a lane ?

### ISSUE THREAD

**Issue by mackoj** [fastlane/sigh#206]
Hi Felix Krause and Fastlane Team,

Thanks for your great tool I'm currently in the process of migrating our own tooling to it.

### Our Setup

We have two team :
- Team1 is our In-House account where we make all of our debug, beta and test build
- Team2 is our Company/Organization account where we do our Ad-Hoc and AppStore build

Our projecy have 5 target :
- TheProject
- TodayExtensions
- WatchApp
- WatchExtensions
- TheProjectWithDebugFiles

For each target we have 9 configurations :

![screen shot 2015-11-10 at 14 47 05](https://cloud.githubusercontent.com/assets/661647/11063929/04c40b08-87ba-11e5-997f-3f7b5fea5df5.png)

It's a pain when someone screw up the config.

### What I try to do

I'm trying to use Fastlane to fix one of our most painful issue which is fixing provisioning issues.
In order to fix it I made this lane `:fix_provisioning`.

I want to :
- repair
- download all
- reassign uuid to the correct configuration/target/provisioning without redownloading the provisioning profiles

In order to simplify the administration of our complex setup I made a provisioning.yml with all configurations.

And I also try to block developer to automatically fixing it by disabling `Fix-it` button with [FixCode](https://github.com/neonichu/FixCode)

### Questions ?

- Can I achieve this with Fastlane ?
- What did I do wrong ? Because it's always re-downloading each mobile provisioning for each configuration. Could we just re-downloading the one which has been modified ? I rather prefer to use previously downloaded ones.
- Can I make it faster(actually it's taking 20 minutes to run) ?

### Feature Request

- Can `install_xcode_plugin` test if a plugin is already installed and if not install it or update it ?

#### Fastfile

```ruby
require 'yaml'

fastlane_version "1.37.0"
default_platform :ios

def fix_provisioning_configuration
  provisioningConfiguration = YAML::load(File.open( [File.dirname(__FILE__), '.', 'provisioning.yml'].join("/")))
  
  provisioningConfiguration.each do |target|
    puts target
    ENV[target["xcode_key"]] = sigh(
      app_identifier: target["app_identifier"],
      output_path: "/tmp", # can't I use the default path where they are all stored ?
      provisioning_name: target["provisioning_name"],
      team_id: target["team_id"],
      team_name: target["team_name"],
      adhoc: target["adhoc"],
      development: target["development"]
    )
  end
end

platform :ios do
  before_all do
  end

  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.1.0/FixCode.xcplugin.zip"
    )
  end

  lane :fix_provisioning do
    system("sigh repair")
    system("sigh download_all")
    fix_provisioning_configuration
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack(message: exception.message,success: false)
  end
end
```

#### provisioning.yml

```yaml
---

- xcode_key:          PROJECT_UDID_CALABASH
  provisioning_name:  T1 iPhone Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_DEBUG
  provisioning_name:  T1 iPhone Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_INTEGRATIONCONTINUE
  provisioning_name:  T1 iPhone inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_LIVRAISON
  provisioning_name:  T1 iPhone inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_LIVRAISONSTAGING
  provisioning_name:  T1 iPhone inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_LIVRAISONVALID
  provisioning_name:  T1 iPhone inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_UITESTS
  provisioning_name:  T1 iPhone Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          PROJECT_UDID_ADHOC
  provisioning_name:  T2 iPhone Adhoc
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2

- xcode_key:          PROJECT_UDID_RELEASE
  provisioning_name:  T2 iPhone Store
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2


- xcode_key:          TODAY_EXTENSIONS_UDID_CALABASH
  provisioning_name:  T1 Today Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_DEBUG
  provisioning_name:  T1 Today Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_INTEGRATIONCONTINUE
  provisioning_name:  T1 Today inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_LIVRAISON
  provisioning_name:  T1 Today inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_LIVRAISONSTAGING
  provisioning_name:  T1 Today inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_LIVRAISONVALID
  provisioning_name:  T1 Today inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_UITESTS
  provisioning_name:  T1 Today Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          TODAY_EXTENSIONS_UDID_ADHOC
  provisioning_name:  T2 Today Adhoc
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2

- xcode_key:          TODAY_EXTENSIONS_UDID_RELEASE
  provisioning_name:  T2 Today Store
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2


- xcode_key:          WATCHKIT_APP_UDID_CALABASH
  provisioning_name:  T1 WatchKit App Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_DEBUG
  provisioning_name:  T1 WatchKit App Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_INTEGRATIONCONTINUE
  provisioning_name:  T1 WatchKit App inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_LIVRAISON
  provisioning_name:  T1 WatchKit App inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_LIVRAISONSTAGING
  provisioning_name:  T1 WatchKit App inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_LIVRAISONVALID
  provisioning_name:  T1 WatchKit App inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_UITESTS
  provisioning_name:  T1 WatchKit App Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_APP_UDID_ADHOC
  provisioning_name:  T2 WatchKit App Adhoc
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2

- xcode_key:          WATCHKIT_APP_UDID_RELEASE
  provisioning_name:  T2 WatchKit App Store
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2


- xcode_key:          WATCHKIT_EXTENSIONS_UDID_CALABASH
  provisioning_name:  T1 WatchKit Extension Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_DEBUG
  provisioning_name:  T1 WatchKit Extension Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_INTEGRATIONCONTINUE
  provisioning_name:  T1 WatchKit Extension inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_LIVRAISON
  provisioning_name:  T1 WatchKit Extension inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_LIVRAISONSTAGING
  provisioning_name:  T1 WatchKit Extension inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_LIVRAISONVALID
  provisioning_name:  T1 WatchKit Extension inHouse
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_UITESTS
  provisioning_name:  T1 WatchKit Extension Dev
  app_identifier:     com.project.bundleid1
  team_id:            HEXA123456
  adhoc:              false
  development:        true
  team_name:          Team1

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_ADHOC
  provisioning_name:  T2 WatchKit Extension Adhoc
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2

- xcode_key:          WATCHKIT_EXTENSIONS_UDID_RELEASE
  provisioning_name:  T2 WatchKit Extension Store
  app_identifier:     com.project.bundleid2
  team_id:            HEXA789123
  adhoc:              true
  development:        false
  team_name:          Team2
```
